name: Hello World Container

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - name: Print hello world
        shell: sh
        run: echo "hello world"
